# Generated by Django 5.1.1 on 2024-10-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0002_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='formatK',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='book',
            name='izdatelstvo',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='book',
            name='kolvostranits',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='book',
            name='pereplet',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='book',
            name='razdel',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AddField(
            model_name='book',
            name='ves',
            field=models.TextField(default='Нет данных'),
        ),
    ]
