# Generated by Django 5.1.1 on 2024-10-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0003_book_formatk_book_izdatelstvo_book_kolvostranits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.TextField(default='Нет данных'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
