# Generated by Django 5.1.1 on 2024-10-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startit_app', '0005_genre_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
    ]
